name: force_it
version: 0.1.3+1
author: Joris Hermans <hermansj@gmail.com>
description: A modern dependency injection like java spring package
homepage: https://github.com/jorishermans/dart-force_it
dependencies:
  forcemirrors: '>=0.1.10 <0.2.0'
  yaml: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'
